config/routes.rb
Rails.application.routes.draw do

  # get "log_in" => "sessions#new", :as => "log_in"
  # get "log_out" => "sessions#destroy", :as => "log_out"

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :admins, only: [:new, :create], path_names: {new: 'sign_up'}

  resources :photos

  root 'pages#index'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  # def Admin.digest(string)
  #   cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
  #                                                 BCrypt::Engine.cost
  #   BCrypt::Password.create(string, cost: cost)
  # end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.authenticate(email, password)
    admin = find_by_email(email)
    if admin && admin.password_hash == BCrypt::Engine.hash_secret(password, admin.password_salt)
      admin
    else
      nil
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def pretty_date
    created_at.to_date.strftime("%m\/\%d\/\%Y")
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :image, ImageUploader
  mount_uploaders :images, ImageUploader
  scope :last_eight, -> { order("created_at desc").last(8) }
  validates :title, :description, :image, :date_taken, :presence => true

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def new

    @admin = Admin.new
  end

  def create
    @admin = Admin.new(admin_params)
    if @admin.save
      redirect_to root_url, notice: "Signed Up"
    else
      render "new"
    end
  end

  private

  def admin_params
    params.require(:admin).permit(:email, :password)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @most_recent = Photo.last_eight
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
  end

  def show
    @photo = Photo.find_by_id(params[:id])
    if @photo.nil?
      redirect_to root_path
    end
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      puts "created"
      redirect_to "/photos"
    else
      render 'new'
    end
  end

  def update
  end

  def destroy
    @photo = Photo.find(params[:id])
    if @photo.destroy
      puts "deleted"
      redirect_back(fallback_location: root_path)
    else
      puts "couldn't delete"
      redirect_back(fallback_location: root_path)
    end
  end

  def edit
    if current_admin
      @photo = Photo.find(params[:id])
    else
      flash.alert = "Sorry, you aren't allowed there."
      redirect_to root_url
    end
  end

  private

  def photo_params
    params.require(:photo).permit(:image, :title, :description, :date_taken, {images: []})
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    admin = Admin.authenticate(params[:session][:email], params[:session][:password])
    if admin
      log_in admin
      redirect_to root_url, notice: "Welcome back #{admin.email}!"
    else
      flash.now.alert = "Invalid email or password."
      render "new"
    end
  end

  def destroy
    session[:admin_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(admin)
    session[:admin_id] = admin.id
  end

  def logged_in?
    !current_admin.nil?
  end

  def current_admin
    @current_admin ||= Admin.find_by(id: session[:admin_id])
  end
end

app/views/admins/new.html.haml
.header-msg
  .row
    .column
      = render "partials/flashes"
      %h1 Create Another Admin
.main-content-container
  .row
    .columns.medium-6
      = simple_form_for @admin do |f|
        - if @admin.errors.any?
          .error-messages
            %h2 Errors
            %ul
              %li= message
        = f.input :email
        = f.input :password
        = f.input :password_confirmation
        = f.button :submit

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en" }
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tag

  %body
    :javascript
      $(function(){ $(document).foundation(); });
    .off-canvas-wrapper
      .off-canvas-wrapper-inner{"data-off-canvas-wrapper" => ""}
        = render "partials/navigation"
        .off-canvas-content{"data-off-canvas-content" => ""}
          .title-bar.hide-for-large
            .title-bar-left
              %button.menu-icon{"data-open" => "sidebar_navigation", :type => "button"}
              .site-title
                %i.fa.fa-truck.fa-lg
                %span.title-bar-title CampCR
          = yield
          %footer
            = render "partials/footer"

app/views/pages/index.html.haml
.header-msg
  .row
    .column
      = render "partials/flashes"
      %h1 Welcome to CampCR!
      %p.lead This is a photo journey of our adventures while traveling across country in our camper.
      %p Take a look around. You'll see the latest few photos below. To see them all click on All!
.main-content-container
  .row
    - @most_recent.each do |photo|
      .large-6.columns.photo-grid-item
        %h2= photo.title
        %p= photo.pretty_date
        - if current_admin
          = link_to "Edit", edit_photo_path(photo)
          = link_to "Delete", photo, method: :delete, data: {confirm: "You sure?"}
        = image_tag photo.image.large, alt: photo.title
        %p= photo.description

app/views/partials/_flashes.html.haml
- flash.each do |name, msg|
  = content_tag :div, msg, id: "flash#{name}"

app/views/partials/_footer.html.haml
.column
  %p
    Copyright &copy;
    = DateTime.now.year
    Mike Costuros

app/views/partials/_navigation.html.haml
#sidebar_navigation.off-canvas.position-left.reveal-for-large{"data-off-canvas" => "", "data-position" => "left"}
  .row.column
    = link_to root_path, class: "site-logo-and-header" do
      %i.fa.fa-truck.fa-4x.nav-link
      %h2.site-title.nav-link CampCR
    %ul
      = link_to photos_path, class: "nav-link" do
        %li All Photos
      - if current_admin
        = link_to new_photo_path, class: "nav-link"  do
          %li Add Photo
        =link_to logout_path(current_admin.id), class: "nav-link", method: "delete" do
          %li Log out
        = link_to new_admin_path, class: "nav-link"  do
          %li New Admin Account
      - else
        = link_to login_path, class: "nav-link"  do
          %li Login

app/views/partials/_photoform.html.haml
= simple_form_for @photo, html: {multipart: true}  do |f|
  = f.input :title
  = f.input :description, as: "text"
  = f.input :date_taken, as: :date
  - if current_page?(action: 'new')
    = f.input :image, as: :file, input_html: { hidden: true, id: "real_file", class: "show-for-sr"}, label: "Upload Photo"
    .input-append
      %input#file-display.input-large.uneditable-input{type: "text", disabled: "disabled"}
      %a#upload-btn.button.warning
        %i.icon-upload-alt Browse
  = f.button :submit, "Save"

app/views/photos/edit.html.haml
.header-msg
  .row
    .column
      = render "partials/flashes"
      %h1 Edit Photo Information
.main-content-container
  .row
    .column
      = image_tag @photo.image.large.url
  .row
    .columns.medium-6
      = render "partials/photoform"

app/views/photos/index.html.haml
.header-msg
  .row
    .column
      = render "partials/flashes"
      %h1 All Photos
.main-content-container
  .row
    - @photos.each do |photo|
      .small-3.columns.photo-grid-item-wide
        = link_to photo_path(photo) do
          = image_tag photo.image.grid, alt: photo.title
        - if current_admin
          = link_to "Edit", edit_photo_path(photo)
          = link_to "Delete", photo, method: :delete, data: {confirm: "You sure?"}

app/views/photos/new.html.haml
.header-msg
  .row
    .column
      = render "partials/flashes"
      %h1 New Photo
.main-content-container
  .row
    .columns.medium-6
      = render "partials/photoform"

app/views/photos/show.html.haml
.header-msg
  .row
    .column
      = render "partials/flashes"
      %h1= @photo.title
.main-content-container
  .row
    .column
      = image_tag @photo.image.large.url, alt: @photo.title
      %p= @photo.description
      - if current_admin
        = link_to "Edit", edit_photo_path(@photo)
        = link_to "Delete", @photo, method: :delete, data: {confirm: "You sure?"}